### ISSUE TITLE
[Mode C]Mode Cの出力でのみアプリが異常終了する

### ISSUE THREAD

**Issue by InuInu2022** [InuInu2022/KotoKanade#22]
- Mode Cの出力でのみアプリが異常終了する
-

**Comment by InuInu2022** [comment]
怪しいのはFFMpegまわり。
高速解析のための並列処理関係も怪しいかも。

**Comment by InuInu2022** [comment]
```
2024-03-25 21:27:57.4842 [ERROR]    at System.ArgumentNullException.Throw(String paramName)
   at System.IO.Path.GetFullPath(String path)
   at KotoKanade.Core.Util.MediaUtil.IsFFMpegDownloaded()
   at KotoKanade.Core.Util.MediaUtil.IsFFMpegInstalledAsync(CancellationToken ctx)
   at KotoKanade.Core.Models.MediaConverter.FactoryAsync(IProgress`1 downloadProgress)
   at KotoKanade.Core.Models.ScoreParser.ProcessPitchAndTimingFromWavAsync(String wavPath, Boolean useWav, SongData songData)
   at KotoKanade.Core.Models.ScoreParser.ProcessCcsAsync(String path, String labPath, String wavPath, Boolean useLab, Boolean useWav)
   at KotoKanade.ViewModels.MainViewModel.<get_ExportEvent>b__122_0()
   at Epoxy.Internal.InternalHelpers.AsValueTaskUnit(ValueTask task) in /_/src/Epoxy.Core/Internal/InternalHelpers.cs:line 80
   at Epoxy.Command.OnExecute(Object parameter) in /_/src/Epoxy.Core/Command.cs:line 61
   at Epoxy.Command.<>c__DisplayClass6_0.<OnExecute>b__0(Boolean _) in /_/src/Epoxy.Core/Command.cs:line 70
   at Epoxy.Internal.InternalUIThread.<>c__DisplayClass0_0.<ContinueOnUIThread>b__0() in /_/src/Epoxy.Core.Avalonia11/Internal/ContinueOnUIThread.cs:line 40
   at Avalonia.Threading.DispatcherOperation.InvokeCore()
   at Avalonia.Threading.DispatcherOperation.Execute()
   at Avalonia.Threading.Dispatcher.ExecuteJob(DispatcherOperation job)
   at Avalonia.Threading.Dispatcher.ExecuteJobsCore(Boolean fromExplicitBackgroundProcessingCallback)
   at Avalonia.Threading.Dispatcher.Signaled()
   at Avalonia.Win32.Win32Platform.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam)
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
   at Avalonia.Win32.Win32DispatcherImpl.RunLoop(CancellationToken cancellationToken)
   at Avalonia.Threading.DispatcherFrame.Run(IControlledDispatcherImpl impl)
   at Avalonia.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken)
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args)
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime(AppBuilder builder, String[] args, Action`1 lifetimeBuilder)
   at KotoKanade.Program.Main(String[] args)
```
